[package]
authors = ["hanabi1224 <harlowmoo@gmail.com>"]
description = "variant config"
edition = "2018"
license = "MIT"
name = "variant-config"
repository = "https://github.com/hanabi1224/VariantConfig"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0"
anyhow = "1"
cranelift = "0.72"
cranelift-jit = "0.72"
cranelift-module = "0.72"
crossbeam-channel = "0"
hashbrown = "0.11"
log = "0"
# notify = "5.0.0-pre.6"
peg = "0.6"
# protobuf = {version = "2", features = ["with-bytes"]}
serde = "1"
serde_json = "1"
serde_yaml = "0"
toml = "0"

[dev-dependencies]
bson = "1"

[build-dependencies]
# protobuf-codegen-pure = "2"

[lib]
crate-type = ["lib", "cdylib"]
