[package]
description = "variant config"
edition = "2021"
license = "MIT"
name = "variant-config"
repository = "https://github.com/hanabi1224/VariantConfig"
version = "0.1.4"

[features]

[dependencies]
ahash = "0.7"
anyhow = "1"
cranelift = "0.82"
cranelift-jit = "0.82"
cranelift-module = "0.82"
hashbrown = "0.12"
log = "0.4"
# notify = "5.0.0-pre.6"
peg = "0.8"
# protobuf = {version = "2", features = ["with-bytes"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_yaml = "0.8.23"
toml = "0.5"

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"]}
# bson = "1"

[build-dependencies]
# protobuf-codegen-pure = "2"

[lib]
crate-type = ["lib", "cdylib"]

[[bench]]
harness = false
name = "benchmarks"
