name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build
        run: cargo build --all-features --release --workspace --exclude web-example
      - name: Test
        run: cargo test --all-features --release --workspace --exclude web-example
      - name: Bench
        run: |
          pushd crates/variant-config
          cargo run --release --all-features --bin bencher
          popd
